version: '3'

services:

  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_MULTIPLE_DATABASES: foaas
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./pg-init.d:/docker-entrypoint-initdb.d